### ISSUE TITLE
Not started with Java 16 [Error]

### ISSUE THREAD

**Issue by WhiTe-Yak** [MinecraftChannel/BungeeCord-BotFilter#3]
proxy.log.0 ->

11:25:40 [FINE] Using manager EnhancedLocalRepositoryManager with priority 10.0 for libraries
11:25:40 [INFO] Using mbed TLS based native cipher.
11:25:40 [INFO] Using zlib based native compressor.
11:25:40 [WARNING] Включаю BungeCord BotFilter 1.8.x-1.17.x от vk.com/Leymooo_s (http://rubukkit.org/threads/137038)
11:25:40 [FINE] Using SLF4J as the default logging framework
11:25:40 [FINE] -Dio.netty.leakDetection.level: simple
11:25:40 [FINE] -Dio.netty.leakDetection.targetRecords: 4
11:25:40 [SEVERE] Exception in thread "main" 
11:25:40 [SEVERE] java.lang.reflect.InaccessibleObjectException: Unable to make private native java.lang.reflect.Field[] java.lang.Class.getDeclaredFields0(boolean) accessible: module java.base does not "opens java.lang" to unnamed module @2baf3d81

11:25:40 [SEVERE] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)

11:25:40 [SEVERE] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)

11:25:40 [SEVERE] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)

11:25:40 [SEVERE] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)

11:25:40 [SEVERE] 	at ru.leymooo.botfilter.config.Config.setAccessible(Config.java:420)

11:25:40 [SEVERE] 	at ru.leymooo.botfilter.config.Config.getField(Config.java:307)

11:25:40 [SEVERE] 	at ru.leymooo.botfilter.config.Config.set(Config.java:54)

11:25:40 [SEVERE] 	at ru.leymooo.botfilter.config.Config.set(Config.java:114)

11:25:40 [SEVERE] 	at ru.leymooo.botfilter.config.Config.load(Config.java:99)

11:25:40 [SEVERE] 	at ru.leymooo.botfilter.config.Settings.reload(Settings.java:238)

11:25:40 [SEVERE] 	at ru.leymooo.botfilter.BotFilter.<init>(BotFilter.java:74)

11:25:40 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)

11:25:40 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:49)

11:25:40 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by WhiTe-Yak** [comment]
Поддержка 1.17
    Для запуска на новых версиях Java добавьте эти флаги в строку запуска перед -jar:
    --illegal-access=permit (не работает на java 17+)
    или
    --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED (должно работать на всех версиях)
